#!/bin/sh
# Build every port of the sharder library, or the ports named on the command line.
#
# A port is built by the `build.sh` its own directory carries, so a port added under `ports/` is
# built by this script and by continuous integration without a change to either.  A port's script
# runs from the port's own directory and exits non-zero where the build fails.
#
#   ./build.sh              build every port
#   ./build.sh java         build the ports named
#   ./build.sh --list       name the ports this script would build, one to a line
#
# The conformance suite is regenerated by `conformance/generator/run.sh`, which this script does
# not run: regeneration takes minutes and produces a byte-identical tree, and a port's build runs
# the suite it already carries.

set -u

cd "$(dirname "$0")"

available() {
    for script in ports/*/build.sh; do
        [ -x "$script" ] || continue
        basename "$(dirname "$script")"
    done
}

usage() {
    echo "usage: ./build.sh [--list] [port ...]" >&2
    exit 2
}

ports=$(available)

if [ "$#" -gt 0 ] && [ "$1" = "--list" ]; then
    [ "$#" -eq 1 ] || usage
    echo "$ports"
    exit 0
fi

if [ "$#" -gt 0 ]; then
    selected=""
    for name in "$@"; do
        case "$name" in
            -*) usage ;;
        esac
        found=no
        for port in $ports; do
            [ "$port" = "$name" ] && found=yes
        done
        if [ "$found" = no ]; then
            echo "no port named $name carries an executable ports/$name/build.sh" >&2
            exit 2
        fi
        selected="$selected $name"
    done
else
    selected="$ports"
fi

if [ -z "$(echo "$selected" | tr -d ' \n')" ]; then
    echo "no port carries an executable build.sh; nothing to build"
    exit 0
fi

failed=""
for port in $selected; do
    echo "== building the $port port"
    if (cd "ports/$port" && ./build.sh); then
        echo "== $port: built"
    else
        echo "== $port: FAILED"
        failed="$failed $port"
    fi
done

if [ -n "$failed" ]; then
    echo "== failed:$failed"
    exit 1
fi

echo "== every port built"
